[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.flash_mode = dio
;upload_port = /dev/cu.usbserial-xxxx  ; macOS: ls /dev/cu.* 查看串口后取消注释
;monitor_port = /dev/cu.usbserial-xxxx

lib_deps =
    ncmreynolds/ld2410@^0.2.1
    olikraus/U8g2@^2.34.22
