[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.flash_mode = dio
upload_port = /dev/cu.usbserial-5C3D0841851
monitor_port = /dev/cu.usbserial-5C3D0841851

lib_deps =
    ncmreynolds/ld2410@^0.2.1
    olikraus/U8g2@^2.34.22
